version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5434/blog_platform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=matijalaki

  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: blog_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: matijalaki
