spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: "[{Matija20}]"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


