spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog_platform
    username: postgres
    password: matijalaki
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
